import React from 'react';
import { Download, Eye, ArrowRight } from 'lucide-react';
import { motion } from 'framer-motion';
import { recentReportsData } from '../../data/reportsData';

export default function RecentReportsTable({ onDownloadReport, onViewReport }) {
  return (
    <div className="bg-white rounded-2xl border border-slate-200/80 shadow-2xs p-4 sm:p-5 flex flex-col justify-between">
      <div>
        <h3 className="text-sm sm:text-base font-black text-[#0B1E36] tracking-tight mb-3">
          Recent Reports
        </h3>

        <div className="overflow-x-auto custom-scrollbar">
          <table className="w-full text-left border-collapse min-w-[700px]">
            <thead>
              <tr className="border-b border-slate-100 text-[10px] font-extrabold text-slate-400 uppercase">
                <th className="pb-2.5 font-bold">Report Name</th>
                <th className="pb-2.5 font-bold">Type</th>
                <th className="pb-2.5 font-bold">Duration</th>
                <th className="pb-2.5 font-bold">Generated On</th>
                <th className="pb-2.5 font-bold">Generated By</th>
                <th className="pb-2.5 font-bold text-right">Actions</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-slate-100 text-xs font-medium text-slate-700">
              {recentReportsData.map((report) => (
                <tr key={report.id} className="hover:bg-slate-50/70 transition-colors">
                  <td className="py-3 font-extrabold text-slate-900 truncate">
                    {report.name}
                  </td>
                  <td className="py-3 text-slate-500 font-semibold">{report.type}</td>
                  <td className="py-3 text-slate-600">{report.duration}</td>
                  <td className="py-3 text-slate-500">{report.generatedOn}</td>
                  <td className="py-3 text-slate-700 font-semibold">{report.generatedBy}</td>
                  <td className="py-3 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <motion.button
                        type="button"
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => onDownloadReport(report)}
                        className="p-1.5 rounded-lg border border-slate-200/90 hover:bg-slate-50 text-slate-600 hover:text-emerald-700 transition-colors cursor-pointer shadow-2xs"
                        title="Download Report"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </motion.button>

                      <motion.button
                        type="button"
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => onViewReport(report)}
                        className="p-1.5 rounded-lg border border-slate-200/90 hover:bg-slate-50 text-slate-600 hover:text-blue-600 transition-colors cursor-pointer shadow-2xs"
                        title="View Report"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </motion.button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Footer Link */}
      <div className="pt-3 border-t border-slate-100 mt-3">
        <button
          type="button"
          className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 cursor-pointer"
        >
          <span>View all reports</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}
